<?xml version="1.0"?>

<!--
Copyright (c) 2020 StreetDrone Limited
Author:  Efimia Panagiotaki

All rights reserved
-->

<robot name="sd_twizy" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find mcav_sd_model)/urdf/bases/sd_twizy_body.gazebo.xacro" />

  <xacro:macro name="sd_twizy_base" params="name">
    <xacro:property name="depth" value="2.352"/>
    <xacro:property name="height" value="1.7"/>
    <xacro:property name="width" value="1.431"/>
    <xacro:property name="base_mass" value="435"/>
    <xacro:property name="clearance" value="0.281"/>

    <xacro:property name = "wheelbase" value="1.686"/>

    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <box size="0.001 0.001 0.001" />
        </geometry>
      </visual>
    </link>

    <joint name="chassis_joint" type="fixed">
      <origin xyz="${wheelbase / 2} 0 0" rpy="0 0 0"/>
      <parent link="base_link"/>
      <child link="chassis"/>
    </joint>

    <material name="chassis_color">
      <color rgba="${223/255} ${249/255} ${252/255} 1.0"/>
    </material>

    <link name="chassis">
      <inertial>
        <mass value="${base_mass}"/>
        <origin xyz="0 0 0"/>
        <inertia ixx="243.175" ixy="0" ixz="0" iyy="430.166" iyz="0" izz="430.166"/>
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="0 0 1.57079632679"/>
        <geometry>
          <mesh filename="file:///$(find mcav_sd_model)/meshes/SDTwizy.stl" scale="0.01 0.01 0.01"/>
        </geometry>
        <material name="chassis_color" />
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 1.57079632679"/>
        <geometry>
          <mesh filename="file:///$(find mcav_sd_model)/meshes/SDTwizy_collision.stl" scale="0.01 0.01 0.01"/>
        </geometry>
      </collision>
    </link>
  </xacro:macro>

</robot>
