name: Build & publish docker images
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - ci_docker

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/Dockerfile.cpu
            image: ghcr.io/Monash-Connected-Autonomous-Vehicle/mcav_autonomy_cpu
          - dockerfile: ./docker/Dockerfile.gpu
            image: ghcr.io/Monash-Connected-Autonomous-Vehicle/mcav_autonomy_gpu
          #- dockerfile: ./docker/Dockerfile.arm
          #  image: ghcr.io/Monash-Connected-Autonomous-Vehicle/mcav_autonomy_arm
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.image }}

      - name: Setup Docker buildx for layer caching
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # for buildx caching of layers
          cache-to: type=gha,mode=max # for buildx caching of layers